--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/sylvrs/PlayerTags
build-by-default: true
branches:
  - master
projects:
  PlayerTags:
    path: ""
    lint:
      phpstan: false
...
