name: PlayerTags
version: 2.0.0
main: sys\jordan\tags\PlayerTagsBase
api: 4.0.0
author: sylvrs
softdepend:
  - AdvancedJobs
  - CombatLogger
  - EconomyAPI
  - FactionsPro
  - KDR
  - PiggyFactions
  - PurePerms
  - RankUp
  - RedSkyBlock
  - SkyBlock