name: PlayerTags
version: 1.0.8
main: sys\jordan\tags\PlayerTagsBase
api:
  - 3.0.0
author: sylvrs
softdepend:
  - AdvancedJobs
  - CombatLogger
  - EconomyAPI
  - FactionsPro
  - KDR
  - PiggyFactions
  - PurePerms
  - RankUp
  - RedSkyBlock
  - SkyBlock