name: PlayerTags
version: 1.0.9
main: sys\jordan\tags\PlayerTagsBase
api: 3.22.1
author: sylvrs
softdepend:
  - AdvancedJobs
  - CombatLogger
  - EconomyAPI
  - FactionsPro
  - KDR
  - PiggyFactions
  - PurePerms
  - RankUp
  - RedSkyBlock
  - SkyBlock