---
##
# For formatting and/or a list of supported tags, visit https://github.com/sylvrs/PlayerTags
##
config-version: 2
# The global tag displayed below the player's name tag
# This tag will be disabled if multi-world.enabled is set to true
tag: ""
# The character used to replace Minecraft's color character (ยง)
color-character: "&"
# How often to update the score tags (in ticks)
update-period: 10
# Multi-world support
multi-world:
  # Enabling this will override the tag listed above, unless the level they are in doesn't have a tag
  enabled: false
  worlds:
    # This will be the tag in the level 'world'
    world: ""
...